CREATE TABLE STUDENT (
    ID SERIAL PRIMARY KEY NOT NULL,
    FIRST_NAME VARCHAR(250),
    MIDDLE_NAME VARCHAR(250),
    LAST_NAME VARCHAR(250),
    BIRTHDAY TIMESTAMP,
    EMAIL VARCHAR(250)
);

CREATE TABLE COURSE (
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR(250),
    DESCRIPTION VARCHAR(1024),
    DURATION INTEGER,
    START_DATE TIMESTAMP,
    FINISH_DATE TIMESTAMP
);

CREATE TABLE ENROLLMENT(
    ID SERIAL PRIMARY KEY NOT NULL,
    COURSE_ID INTEGER REFERENCES COURSE(id),
    STUDENT_ID INTEGER REFERENCES STUDENT(id)
);